name: smarthive
base: core18
version: '1.0+git'
summary: Smart Hive Cloud controller
description: |
    Smart Hive Cloud controller snap

grade: stable
confinement: strict

parts:
  smarthive:
    plugin: python
    python-version: python3
    source: https://github.com/SmartHiveAI/smarthive-snap.git
    build-packages:
      - python-gssapi
    python-packages:
      - AWSIoTPythonSDK
      - six
