name: smarthive
base: core18
version: '0.0.4'
summary: Smart Hive Cloud controller
description: |
    Smart Hive Cloud controller snap

grade: stable
confinement: strict

apps:
  smarthive:
    command: usr/bin/python3 $SNAP/bin/smarthive
    daemon: simple
    plugs: [network, network-bind, bluetooth-control]

parts:
  smarthive:
    plugin: python
    python-version: python3
    source: https://github.com/SmartHiveAI/smarthive-snap.git
    stage-packages:
      - python-six
    build-packages:
      - python-gssapi
    python-packages:
      - AWSIoTPythonSDK
